# Dockerfile.jenkinsAgent
FROM tremendousure/sortlog:latest
ARG JENKINSUID
ARG JENKINSGID
ARG DOCKERGID

RUN groupadd -g ${JENKINSGID} jenkins
RUN groupmod -g ${DOCKERGID} docker
RUN useradd -c "Jenkins user" -g ${JENKINSGID} -G ${DOCKERGID} -M -N -u ${JENKINSUID} jenkins

RUN mkdir -p "/home/jenkins" && chown -R jenkins "/home/jenkins" 