name: Deploy Github Pages
on:
  push:
    branches:
      - main
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Check build
        run: |
          yarn
          yarn pre-commit
          yarn export
          touch out/.nojekyll
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          folder: ./out
          branch: gh-pages
          clean-exclude: pr-preview